name: Check Blox Fruits Stock

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  check-stock:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: npm start

      - name: Guardar cambios del anti spam
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/last-alert.json
          git commit -m "Update alert history" || exit 0
          git pull --rebase origin main
          git push
